# Generated by Django 4.0.4

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 14, 16, 23, 331744, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='subject',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 14, 16, 23, 331744, tzinfo=utc)),
        ),
    ]
